### ISSUE TITLE
Potential issue with beardlib?

### ISSUE THREAD

**Issue by kolekelley2** [GreatBigBushyBeard/PAYDAY-2-BeardLib#3]
As of the most recent workshop update and Beardlib update, I have been receiving a crash related to:

lib/setups/gamesetup.lua:298                        
core/lib/setups/coresetup.lua:295  

lib/setups/gamesetup.lua:298 comes out to managers.navigation = NavigationManager:new()

Beardlib calls for NavigationManager in line 11 of mod.txt
{ "hook_id" : "lib/managers/navigationmanager", "script_path" : "BeardLibCore.lua"},

**Comment by GreatBigBushyBeard** [comment]
Could you give more details on the crash? And the line numbers that are displayed in the crash log are not accurate so the line it says does not directly translate to what you'll see in a decompile. Additionally BeardLib hooking to that lua file is irrelevant because it isn't actually used, it is an old one that wasn't removed from when we moved the BeardLib Editor outside of the main BeardLib verison.

**Comment by kolekelley2** [comment]
Hi GBBB!

Sorry for not responding :)

This happens between any day I switch. if I host all clients crash. If I'm client I'll crash between every day.

Full crashlog http://pastebin.com/iN4ECZ4g

**Comment by GreatBigBushyBeard** [comment]
That crash specifically appears to be directly related to package loading, which in that particular area is not touched by BeardLib. I would suggest verifying your game as that crash suggests that you have corrupt assets.

**Comment by kolekelley2** [comment]
Thanks I'll look into this
